### ISSUE TITLE
Cache Taptree height in the TapTree data structure instead of computing it everytime

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-miniscript#430] opened 2022-06-09 01:32 UTC
This would involve:
1) Renaming the existing `TapTree` as `TapTreeInner`. 
2) Adding a field `height` in the newly renamed `Taptree`.

```rust
    // TODO: Instead of computing this every time we add a new leaf, we should
    // add height as a separate field in taptree
    fn taptree_height(&self) -> usize {
        match *self {
            TapTree::Tree(ref left_tree, ref right_tree) => {
                1 + max(left_tree.taptree_height(), right_tree.taptree_height())
            }
            TapTree::Leaf(..) => 0,
        }
    }
```

**Comment by Eunoia1729** [comment] 2022-06-11 00:39
I have a follow-up query:
1. Does a TapTree's structure ever change (i.e. addition or removal of nodes) once instantiated? Looking at the code, my naive understanding is it doesn't.
2. From the TODO comment, its apparent that we want to compute during struct instantiation. But, that would require us creating a module or enforcing instantiation using a method instead of statements such as `TapTree::Tree(left_node, right_node);`. Do we intend to go in this route or did I get it wrong?

**Comment by sanket1729** [comment] 2022-06-11 00:48
1. It does not change once it is instantiated

2. Yes, we intend to go the same route as you suggested.

**Comment by Eunoia1729** [comment] 2022-06-11 10:17
@sanket1729 Thanks for clarifying!

**Comment by ameya-deshmukh** [comment] 2023-02-28 13:51
Hey, I'd like to take this up! Will submit a PR soon

**Comment by apoelstra** [comment] 2023-02-28 21:08
Thanks @ameya-deshmukh ! Heads up that we will be doing a major release this week and won't be able to take in any major changes until after that.

**Comment by ameya-deshmukh** [comment] 2023-03-01 10:18
Sure! I'll still submit a PR though, when it gets reviewed and merged is up to you 😄

**Comment by startup-dreamer** [comment] 2023-04-05 20:00
@apoelstra, @sanket1729  ok i guess the issue is pretty straight can you assign me to implement this

**Comment by wthrajat** [comment] 2023-10-30 17:31
Hi @sanket1729. I was really looking to work for this issue but seems like this one has already been solved by @tcharding in apparently [this commit](https://github.com/rust-bitcoin/rust-miniscript/commit/476e358f27d97ffa43d1d666f132fef40e9033ad). Also some other commits included the renaming of `taptree_height` -> `height` ([commit](https://github.com/rust-bitcoin/rust-miniscript/commit/ecf876ed6238d0482a5b5cc9d2151eaba44d2911)).
Safe to close the issue now I guess? :)

**Comment by apoelstra** [comment] 2023-10-31 13:35
Yep, thank you for finding this @wthrajat!

This is what we get for using code TODOs instead of issues :).

Fixed by https://github.com/rust-bitcoin/rust-miniscript/pull/588

**Closed by apoelstra** 2023-10-31 13:35 UTC
Labels: good first issue
